version: '3'

services:

  minio:
    container_name: minio
    image: minio/minio:latest
    restart: always
    ports:
      - 9000:9000
      - $CONSOLE_PORT:$CONSOLE_PORT
      - 33831:33831
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
      MINIO_API_SELECT_PARQUET: $MINIO_API_SELECT_PARQUET
      CONSOLE_PORT: $CONSOLE_PORT
    volumes:
      - ${DATADIR}/minio/data:/data
      - ${DATADIR}/minio/config:/root/.minio
      - ./scripts:/scripts
    # command: server /data
    entrypoint: /bin/sh
    command: scripts/init.sh

networks: 
  
  default: 
    external: 
      name: datafuel-local-network